export const projectList = [
  {
    logo: "/assets/project-logo/eyelink.webp",
    title: "EyeLink",
    description: [
      "Built and deployed a full-stack accessibility platform used by over 120+ test users, enabling real-time ASL communication and navigation for the differently-abled.",
      "Integrated 3 core modules—ASL translation, voice-guided navigation, and travel assistance—into a unified platform with 95%+ feature uptime.",
      "Achieved WCAG 2.1 compliance to ensure inclusive access, reducing onboarding time by 60% for first-time users with accessibility needs.",
    ],
    projectUrl: "https://asl-neon.vercel.app/",
    gitHubUrl: "https://github.com/Angelgupta13/Eyelink",
    year: "2024",
    languages: [{ name: "Next.js" }, { name: "Google Maps API" }],
  },
  {
    logo: "/assets/project-logo/sonara.webp",
    title: "Sonara",
    description: [
      "Developed a real-time ASL-to-text translation system with 92%+ gesture recognition accuracy using CNN and MediaPipe for robust hand tracking.",
      "Trained on a custom dataset of 10,000+ labeled signs, ensuring consistent performance in dynamic lighting and background conditions.",
      "Deployed using TensorFlow Lite, reducing model inference time by 40% and improving real-time responsiveness for web integration.",
    ],
    projectUrl: "",
    gitHubUrl: "https://github.com/Angelgupta13/Sonara",
    year: "2024",
    languages: [
      { name: "Python" },
      { name: "OpenCV" },
      { name: "MediaPipe" },
      { name: "TensorFlow" },
    ],
  },
  {
    logo: "/assets/project-logo/examassist.webp",
    title: "Exam Assist",
    description: [
      "Built inclusive exam assistance platform connecting certified writers with disabled students.",
      "Achieved 92% user satisfaction through secure, real-time communication using advanced NLP techniques.",
    ],
    projectUrl: "",
    gitHubUrl: "https://github.com/Angelgupta13/exam-assist",
    year: "2024",
    languages: [
      { name: "React" },
      { name: "Node.js" },
      { name: "MongoDB" },
      { name: "TensorFlow" },
    ],
  },
  {
    logo: "/assets/project-logo/drishti.webp",
    title: "Dristhi",
    description: [
      "Engineered a lightweight object detection system using YOLOv5, achieving 87.3% mAP@0.5 on a custom indoor navigation dataset.",
      "Integrated voice feedback for obstacle warnings, improving real-time navigation accuracy by 65% for visually impaired users during trials.",
      "Optimized video frame processing pipeline to maintain 25 FPS on mid-range devices, ensuring smooth live detection UX.",
    ],
    projectUrl: "",
    gitHubUrl: "https://github.com/Angelgupta13/Drishti",
    year: "2024",
    languages: [
      { name: "YOLOv5" },
      { name: "OpenCV" },
      { name: "PyTorch" },
      { name: "Computer Vision" },
    ],
  },
  {
    logo: "/assets/project-logo/blogverse.webp",
    title: "BlogVerse",
    description: [
      "Built a high-performance blog platform using React.js with Markdown support, enabling seamless publishing of 100+ blog entries in testing.",
      "Implemented responsive frontend with shadcn/ui, achieving 88% user satisfaction in document conversion experience.",
      "Designed a mobile-first, fully responsive UI using ShadCN and Tailwind, improving session duration by 55% on mobile devices.",
    ],
    projectUrl: "",
    gitHubUrl: "https://github.com/Angelgupta13/Blogverse",
    year: "2024",
    languages: [{ name: "React" }, { name: "MongoDB" }, { name: "Express.js" }],
  },
];
